n1 = int(input("digite n1: "))
n2 = int(input("digite n2: "))
print(f"{n1} + {n2} = {n1 + n2}")
print(f"{n1} * {n2} = {n1 * n2}")
print(f"{n1} - {n2} = {n1 - n2}")
print(f"{n1} / {n2} = {n1 / n2}")